### ISSUE TITLE
cattrs doesn't work with Python 3.9

### ISSUE THREAD

**Issue by playpauseandstop** [Tinche/cattrs#100]
* cattrs version: 1.0.0
* Python version: 3.9.0
* Operating System: macOS 10.15.6

### Description

I'm trying to use `cattrs==1.0.0` with Python 3.9.0 project, but not able due to `ImportError` described below.

### What I Did

Running,

```bash
.venv/bin/python3 -c 'import cattr'
```

Results in next `ImportError`,

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.9/site-packages/cattr/__init__.py", line 2, in <module>
    from .converters import Converter, UnstructureStrategy
  File ".venv/lib/python3.9/site-packages/cattr/converters.py", line 15, in <module>
    from ._compat import (
  File ".venv/lib/python3.9/site-packages/cattr/_compat.py", line 87, in <module>
    from typing import _Union
ImportError: cannot import name '_Union' from 'typing' (/Users/playpauseandstop/.pyenv/versions/3.9.0/lib/python3.9/typing.py)
```

**Comment by Tinche** [comment]
You can give master a shot, it's tested on 3.9 but still unreleased (in a few days).

**Comment by playpauseandstop** [comment]
Can confirm that `cattrs==1.1.1` has Python 3.9 support and everything works as expected.

Closing this issue as result.

Thanks for fixing this, @Tinche!
