### ISSUE TITLE
Structuring a subset of input keys.

### ISSUE THREAD

**Issue by asford** [Tinche/cattrs#35]
*Feature proposal/request.*
*@Tinche Would you be open to a pull with this feature added an optional flag on `Converter`?*

One scenario I've frequently encountered is the need to extract a *subset* of data from an unstructured input blob. This occurs, for example, when processing a potentially-heterogeneous record from a backend or an external API call when only *some* of the result is required. It would be *very* useful in those scenarios to support a "tolerant" structuring mode for `attrs`-based classes, in which extra keys within the unstructured data are ignored rather than passed into the attrs constructor.

As a minimal motivating example, consider the canonical github `ping` webhook. All I may want to know from the hooked could be summarized in:

```python
import attr

@attr.s(auto_attribs=True)
class Repo:
    full_name: str

@attr.s(auto_attribs=True)
class Ping:
    zen: str
    hook_id: int
    repository: Repo
```

However, the payload of the ping includes:
```
{
  "zen": "Practicality beats purity.",
  "hook_id": 1663 
  "hook": {
    "type": "Repository",
    "id": 1663
    "name": "web",
    ... full hook details ...
  },
  "repository": {
    "id": 314159,
    "name": "name",
    "full_name": "full/name",
    "owner": {
      "login": "asford",
      ... owner details ...
    },
    "private": false,
    ... dozens of urls...
    "created_at": "2018-06-09T17:06:29Z",
    "updated_at": "2018-06-14T09:42:29Z",
    "pushed_at": "2018-06-14T09:42:27Z",
    ... repo details ...
  },
  "sender": {
    "login": "asford",
    ... sender details ...
  }
}
```

I would be *great* if I could initialize a custom `Converter` with a tolerant parsing mode to extract this subset, performing type checking and structuring over the attributes I've defined but silently dropping the "extra" information coming from the api body:

```
ping_body = cattr.Converter(ignore_extra_attribs=True).structure(body, Ping)
```

**Comment by Tinche** [comment]
It's definitely an interesting idea we should support, I'm just not sure adding a flag to the converter is the best way of going about it.

I basically have two things on the cattrs roadmap in my head. One is better union support (unrelated to this), the other is generating structuring/unstructuring functions.

Currently, doing structuring/unstructuring using cattrs is slower than writing the code by hand. This is because we use generic functions. When structuring, we iterate over all fields of a class, get the type, do the dispatch.

It'd be much more efficient if we had ways of generating specialized functions. Given an annotated class, piece together a Python function to structure that class, eval it and register it for that class. This function would be just as fast as a hand written one.

Then, the function that generates this function could have arguments. And you could ask it to generate an unstructuring function that ignores extra attributes.

If you feel like contributing, getting started with this would be the way to go. I'm open to providing feedback :)

**Comment by asford** [comment]
#19 Also seems relevant to this discussion for similar reasons.

**Comment by Tinche** [comment]
Yeah, my idea was tying these to converters, not the classes themselves. Ideally, we would later have an additional converter class that would automatically generate and cache these, and that class would become the default.

For the first pass, imagine the generator being just a function (i.e. not a method on a converter) with the following signature:

```
def make_dict_structure_fn(cl, converter, ignore_unknown_attribs=False) -> Callable[Mapping, Type]:
    ...
```
(You need the converter in there to recursively call for nested attrs classes.)

Then you could just do:
```
converter.register_structure_hook(Ping, make_dict_structure_fn(ping, converter, ignore_unknown_attribs=True))
```
(Later we can make this a method on the converter, but that method should probably call back to this function so very advanced cases can mix converters.)

**Comment by asford** [comment]
Yes, this is a reasonable strategy. This simplest starting implementation is to just call back through the `Converter` dispatch mechanism for every field, which is unlikely to achieve a *significant* performance increase. You'd expect to see bigger gains if you bypass dispatch and inline conversion code for basic data types, which may be a reasonable assumption *if* you make the assertion that the converter behavior (eg. `dict_factory`, `unstruct_strat`, metadata-base control) is immutable.

I'm happy to make contributions to this, as I've already developed a viable workaround for the core issue, but would like to make sure you've a good benchmark set in place *before* launching into any perf tuning. My recommendation would be to establish a few baseline [`pytest-benchmark`](https://github.com/ionelmc/pytest-benchmark) test cases before launching into any work, and then begin working on any optimization from there. Would you be open to a pull of that work?

**Comment by Tinche** [comment]
I think there might actually be some performance gains anyway since we can do the dispatch at generation time instead of on every structure/unstructure.

As for benchmarking, I use Victor Stinner's perf tool (http://perf.readthedocs.io/en/latest/, pip install perf) and I really like it. Here's a quick way to benchmark unstructuring a simple class, containing a string, int and a float:
```
> pyperf timeit -g -s "from cattr import unstructure; import attr; C=attr.make_class('C', {'a': attr.ib(type=str), 'b': attr.ib(type=int), 'c': attr.ib(type=float)}); c = C('1', 2, 3.0)" "unstructure(c)" --fast
...........
3.16 us: 1 ##########################
3.17 us: 1 ##########################
3.19 us: 1 ##########################
3.21 us: 3 ###############################################################################
3.23 us: 2 #####################################################
3.25 us: 0 |
3.26 us: 1 ##########################
3.28 us: 3 ###############################################################################
3.30 us: 2 #####################################################
3.32 us: 1 ##########################
3.34 us: 0 |
3.36 us: 0 |
3.37 us: 1 ##########################
3.39 us: 0 |
3.41 us: 1 ##########################
3.43 us: 0 |
3.45 us: 0 |
3.46 us: 1 ##########################
3.48 us: 0 |
3.50 us: 1 ##########################
3.52 us: 1 ##########################

Mean +- std dev: 3.30 us +- 0.11 us
```
It's a little unwieldy, so I usually define my classes in a helper file and import them from there.

**Comment by gregbrowndev** [comment]
Just wanted to add my own use-case that I've just ran into: that is parsing data from an external API which contains illegal Python identifiers. In addition to containing many items that I'm not interested in, the JSON also contains keys such as `$type`. Resulting the error:

> TypeError: __init__() got an unexpected keyword argument '$type'

It would be great to just ignore un-modelled parts of the shape. 

Many thanks!

**Comment by tefra** [comment]
Same scenario with @gregbrowndev dealing with a very inconsistent api, to deal with until this becomes official we created a base model and registered a custom hook which is almost the same with the default `structure_attrs_fromdict` except that it starts with a fresh dictionary 

```python
def structure_attrs_fromdict(obj, cl):
    # type: (Mapping, Type) -> Any
    """Instantiate an attrs class from a mapping (dict)."""
    # For public use.
    
    # conv_obj = obj.copy()  # Dict of converted parameters.
    conv_obj = dict() # Start fresh

    # dispatch = self._structure_func.dispatch
    dispatch = cattr.global_converter._structure_func.dispatch # Ugly I know
    for a in cl.__attrs_attrs__:
        # We detect the type by metadata.
        type_ = a.type
        if type_ is None:
            # No type.
            continue
        name = a.name
        try:
            val = obj[name]
        except KeyError:
            continue
        conv_obj[name] = dispatch(type_)(val, type_)

    return cl(**conv_obj)

cattr.register_structure_hook(BaseModel, structure_attrs_fromdict)
```

**Comment by gregbrowndev** [comment]
Awesome thanks @tefra, worked like a charm!

Do you have any suggestions on how you might improve my implementation of your solution on my base class? I want to maintain a static converter instance on the base so I can provide a `classmethod` wrapper around the `structure` method. The `init_converter` method provides a converter with some sensible defaults. This works but the coupling of static initialisation made things messy. Any points would be appreciated!


```py
import cattr

def init_converter():
    converter = cattr.Converter()
    converter.register_unstructure_hook(datetime, lambda dt: dt.isoformat() + 'Z')
    converter.register_structure_hook(datetime, lambda ts, _: parser.parse(ts))
    return converter

# Annotate factory function on base class
# see https://github.com/python/typing/issues/58
T = TypeVar('T', bound='Serializable')

class Serializable(object):
    """Serializable mixin with cattr methods for (de)serialization"""
    converter: ClassVar[cattr.Converter]

    @classmethod
    def structure(cls: Type[T], data: Any) -> T:
        return cls.converter.structure(data, cls)

    def unstructure(self) -> Any:
        return self.converter.unstructure(self)

# register hook globally on Serializable
cattr.register_structure_hook(Serializable, structure_attrs_fromdict)

# statically initialize private converter on Serializable
Serializable.converter = init_converter()

# register again as globally registered hook did not seem to be passed to private converters?
Serializable.converter.register_structure_hook(Serializable, structure_attrs_fromdict)
```

**Comment by petergaultney** [comment]
I've run into this myself, also in the context of building APIs where I want strong types internal to the codebase. I've just started using `attrs` and `cattrs`, so I'm no expert. But I came up with this, possibly not very elegant, workaround that is at least a little less code than the things posted so far. I'm sure it's not particularly performant, but that's not as big an issue for me as keeping the codebase as clean as possible. 

```
from typing import Set
from cattr import structure


def drop_nonattrs(d: dict, Type: type) -> dict:
    """gets rid of all members of the dictionary that wouldn't fit in the given 'attrs' Type"""
    if not Type.__attrs_attrs__:
        raise ValueError(f'type {Type} is not an attrs class')
    attrs: Set[str] = {attr.name for attr in Type.__attrs_attrs__}

    return {key: val for key, val in d.items() if key in attrs}


def structure_ignore_extras(d: dict, Type: type):
    return structure(drop_nonattrs(d, Type), Type)
```

The usage is then just `structure_ignore_extras(mydict, MyAttrsType)` where MyAttrsType has been annotated with `@attr.s`.

Let me know if this looks crazy. And I'm looking forward to a more canonical implementation making it into cattrs someday.

**Comment by Tinche** [comment]
I'm thinking making the fresh dict approach (i.e. ignoring extra keys) the standard in the next release. The tests pass with it. Not sure it'll technically be backwards compatible, but it'll be backwards compatible enough I don't care, and probably having a more lenient structurer is a better default.

**Comment by sobolevn** [comment]
@Tinche what is the status of this issue? Currently it does not work for me.

```ipython
In [2]: import attr, cattr

In [3]: @attr.s(auto_attribs=True)
   ...: class Test:
   ...:     x: int
   ...:     y: int
   ...:

In [4]: cattr.structure({'x': 1, 'y': 2, 'z': 3}, Test)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-6dd536a67ff4> in <module>
----> 1 cattr.structure({'x': 1, 'y': 2, 'z': 3}, Test)

~/Documents/PyCharmProjects/kira/.venv/lib/python3.6/site-packages/cattr/converters.py in structure(self, obj, cl)
    176         """Convert unstructured Python data structures to structured data."""
    177         # type: (Any, Type) -> Any
--> 178         return self._structure_func.dispatch(cl)(obj, cl)
    179
    180     # Classes to Python primitives.

~/Documents/PyCharmProjects/kira/.venv/lib/python3.6/site-packages/cattr/converters.py in structure_attrs_fromdict(self, obj, cl)
    296             conv_obj[name] = dispatch(type_)(val, type_)
    297
--> 298         return cl(**conv_obj)
    299
    300     def _structure_list(self, obj, cl):

TypeError: __init__() got an unexpected keyword argument 'z'
```

Versions:

```
attrs==18.2.0
cattrs==0.9.0
```

**Comment by petergaultney** [comment]
And as much as I'd love to see this be the new default, I would also be happy to see a boolean flag that could get passed down recursively (or, I suppose, just set on the converting context) to toggle the behavior.

**Comment by Tinche** [comment]
Try installing cattrs==1.0.0rc0, I haven't made a proper release yet, and let me know if it works for you!

**Comment by hulucc** [comment]
It works for me after updated to 1.0.0rc0

**Comment by decentral1se** [comment]
Thanks for the updated `cattrs==1.0.0rc0` which skips unknowns for me!

Really great library, much <3

**Comment by techdragon** [comment]
@Tinche Having only had trouble with the 'invalid attribute' case like @gregbrowndev did, I'm a little uncomfortable having such a major behaviour switch without a deprecation period. I can see the utility of having a way to only structure the subset you want, but I can say for certain that this will make it harder to use for building round trip serializer/deserializer tools for poorly/undocumented JSON based formats. 

My normal format "reverse engineering" workflow is.
1. Gather a bunch of example files.
2. Write a out a hierarchy of `attrs` based classes. 
3. Use `cattrs` to try and serialize from the JSON based files to python objects.

If I missed anything, like an optional field that isn't in all of the example files... The old behaviour raised errors so I could fix the `attrs` class hierarchy. The new behaviour if left as a default without any configuration change, will basically make it impossible for me to rely on `cattrs` when I wan't to build a *round trip* tool since if I silently drop data during structuring, I'll be silently corrupting configuration/save/etc files that other applications use.

I'm with @petergaultney that we need some kind of flag. Otherwise I don't see how this is a safe default. I'd go so far as to argue that the default should be errors and the subset should be the optional behaviour.

**Comment by petergaultney** [comment]
Arguably, `attrs` isn't really the right tool for dealing with round-trip data. Frankly, I see this as a general weakness of Python - you sort of have to "choose" between statically typed structures that drop things on the floor, or use pure Python types (dicts/lists/sets) but make it much harder to do object-oriented things with them (and static typing becomes harder as well, though TypedDict is a good alternative here). 

Of course, this is _Python_, so you never *really* have to choose, as long as you're willing to do some arguably strange stuff. 

I've actually implemented my own layer on top of `attrs`/`cattrs` that handles round-tripping by effectively putting a magical `dict` inside every attrs class which is accessible via normal dict access methods, and then writing a wrapper around `cattrs` structuring that takes unknown keys and puts them directly into that `dict` inside the object.  See https://github.com/Tinche/cattrs/issues/61 for my request to add some version of this behavior directly to `cattrs` - my workaround at the moment is to apply this behavior directly to my `attrs` classes with a custom decorator.

**Comment by petergaultney** [comment]
Incidentally, I keep thinking about trying to open-source this, but haven't gotten around to it principally because I'm not sure how many people would actually care. It's good to know that there's at least one other person out there facing somewhat similar questions about how to round-trip arbitrary data while also overlaying nice types on top of it.

**Comment by petergaultney** [comment]
Ah, I finally found the other issue where I'd mentioned I might open-source this.

It's called `typecats`. It does a couple of things on top of the "partial typing" behavior I've mentioned, but the stuff we're talking about here is feature #3, called a 'wildcat class'. https://pypi.org/project/typecats/

It's definitely a bit on the weird side, but it works beautifully for roundtripping data, and it also works great for gradual static typing - you can define an empty object that is actually just a `dict`, and then as you go you can add new attributes/types to it without requiring that other keys get dropped at structure time.

**Comment by gvoysey** [comment]
thanks very much for the prerelease @Tinche , this is a lovely feature for ingesting user data.

**Comment by ervteng** [comment]
Hi @Tinche, is the reverse behavior still possible/enableable? i.e. I'd like to throw an error (or at least print a warning) if the unstructured data has fields not found in the `attrs` classes.

**Comment by Tinche** [comment]
@ervteng please create a different issue for this functionality, closing this :)
