### ISSUE TITLE
fix python 3.7

### ISSUE THREAD

**Issue by sky-code** [Tinche/cattrs#37]
* cattrs version: 0.8.1
* Python version: 3.7.0
* Operating System: Mac OS High sierra

### Description

`cattrs` does not work with python 3.7.

### What I Did

```
Traceback (most recent call last):
  File "/Users/macbook/virtualenvs/venom_venv/lib/python3.7/site-packages/natrixclient/client.py", line 8, in <module>
    import cattr
  File "/Users/macbook/virtualenvs/venom_venv/lib/python3.7/site-packages/cattr/__init__.py", line 2, in <module>
    from .converters import Converter, UnstructureStrategy
  File "/Users/macbook/virtualenvs/venom_venv/lib/python3.7/site-packages/cattr/converters.py", line 2, in <module>
    from typing import (
ImportError: cannot import name '_Union' from 'typing' (/Users/macbook/.pyenv/versions/3.7.0/lib/python3.7/typing.py)

Process finished with exit code 1
```

**Comment by Tinche** [comment]
Ugh, gonna have to take a look at this.

**Comment by arnimarj** [comment]
This is how the `typing-inspect` module implemented `is_union_type()`: https://github.com/ilevkivskyi/typing_inspect/blob/master/typing_inspect.py#L119

I believe it supports Python 3.7

**Comment by Tinche** [comment]
Helpful, thanks!

**Comment by Tinche** [comment]
Hi,

I've started a branch for 3.7 but I'm visiting a client this week so it's on hold for a few days.

**Comment by Tinche** [comment]
Should be fixed!

**Comment by Akuli** [comment]
@Tinche i found the problem, `src/cattr/_compat.py` has `is_py37 = version_info[:2] == (3, 7)` when it should be `is_py37 = version_info[:2] >= (3, 7)`, `is_py3` is also similarly broken but there's no hurry with fixing that one

**Comment by splendido** [comment]
same error showing up with Python 3.5.2 with both cattrs==0.9.0
shouldn't it be `from typing import Union`?

**Comment by Akuli** [comment]
works for me in 3.5.3, and at least in 3.5.3, both are the same thing even though `Union` should be used instead of `_Union`

i'm not sure why the code is messing up with `_stuff` in the first place? looks like an ugly hack to me

**Comment by Akuli** [comment]
@splendido try installing the latest version directly from github

```
python3.5 -m pip uninstall cattrs
python3.5 -m pip install git+https://github.com/Tinche/cattrs/
```

or if you don't have git installed

```
python3.5 -m pip uninstall cattrs
python3.5 -m pip install https://github.com/Tinche/cattrs/archive/master.zip
```

**Comment by Akuli** [comment]
@splendido stop using sudo with pip, that's a bad idea, use `--user` instead:

    pip3 install --user git+https://github.com/Tinche/cattrs/

this lib sucks i guess

**Comment by Tinche** [comment]
The tests for 3.5 use 3.5.5. I seem to remember versions of 3.5 prior to 3.5.3 having a different `typing` module, and supporting legacy minor versions is just not worth it honestly.

As for why _Union is used, it's to make it usable with singledispatch. The typing module is kinda half-baked, and this is far from the only hack we use.
